In [2]:
import numpy as np

In [29]:
fun = lambda x: np.diff(x, axis=0)

In [30]:
#apply function to each element of x
y = np.apply_along_axis(fun, 1, x)


In [27]:
y.shape

(4, 2, 1)

In [44]:
x = np.random.uniform(-1,1,size=(5,10,2))

In [45]:
fun(x[0])

array([[-1.15069322, -0.4449525 ],
       [-0.43684808, -0.52203752],
       [ 1.33571646,  1.58906737],
       [-0.8896034 , -1.43357548],
       [ 0.36739624,  1.13582609],
       [ 0.37401694, -0.87341749],
       [-0.73957678,  0.15149567],
       [ 0.8587657 ,  1.09846119],
       [-0.43340972, -0.63942752]])

In [43]:
x[0]

array([[ 0.04529219],
       [-0.63016771],
       [-0.78555292],
       [ 0.62843263],
       [ 0.61611348],
       [-0.90740428],
       [ 0.49489281],
       [-0.09675172],
       [ 0.84478075],
       [-0.71773361]])

In [47]:
fun = lambda x: x[1:]-x[:-1]

In [49]:
 np.apply_along_axis(fun, 1, x).shape

(5, 9, 2)

In [57]:
fun = lambda x: np.r_[x[1:,0]-x[:-1,0], x[1:,1]-x[:-1,1]]

In [65]:
#vectorize [fun(x[0]),fun(x[1]),fun(x[2]),fun(x[3]),fun(x[4])... ] 
y = np.apply_along_axis(fun, 1, x)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [16]:
import numpy as np

# Definiamo una funzione che prende un array T x M e restituisce un vettore di dimensione K
def my_function(matrix):
    # Per esempio, possiamo fare la somma lungo l'asse 0 e l'asse 1
    # e concatenare i risultati per ottenere un vettore di dimensione K = 2
    return np.concatenate([np.sum(matrix, axis=0), np.sum(matrix, axis=1)])


In [28]:
import numpy as np

# Definiamo una funzione che prende un array T x M e restituisce un vettore di dimensione K
def my_function(matrix):
    sum0 = np.sum(matrix, axis=0)  # somma lungo l'asse 0
    sum1 = np.sum(matrix, axis=1)  # somma lungo l'asse 1
    return np.concatenate((sum0, sum1))  # restituisce la concatenazione

# Creiamo un array di dimensione N x T x M
N, T, M = 5, 3, 4
array = np.random.rand(N, T, M)

# Funzione wrapper per applicare my_function
def apply_my_function(arr):
    return my_function(arr)

# Vectorize la funzione
vectorized_function = np.vectorize(apply_my_function, signature='(m,n)->(k)')

# Applichiamo la funzione vettorializzata all'array
result = vectorized_function(array)

# Assicuriamoci che il risultato abbia la forma corretta N x K
K = result.shape[-1]
result = result.reshape(N, K)

print(result)


[[1.91451841 2.19051299 0.36889504 1.23071382 2.04557391 2.32803452
  1.33103183]
 [1.47501828 1.43803854 1.30485999 1.60275897 1.84492292 2.51982117
  1.45593168]
 [1.41751865 1.68625631 1.56411921 1.03450278 2.1320123  2.20178658
  1.36859807]
 [2.22038617 0.70434583 1.47422905 1.63413118 1.9859865  1.43115841
  2.61594734]
 [1.68435607 1.82414766 1.60309226 1.25991822 2.22449292 1.45932154
  2.68769974]]


In [31]:
vectorized_function = np.vectorize(my_function, signature='(m,n)->(k)')

# Applichiamo la funzione vettorializzata all'array
result = vectorized_function(array)


[[1.91451841 2.19051299 0.36889504 1.23071382 2.04557391 2.32803452
  1.33103183]
 [1.47501828 1.43803854 1.30485999 1.60275897 1.84492292 2.51982117
  1.45593168]
 [1.41751865 1.68625631 1.56411921 1.03450278 2.1320123  2.20178658
  1.36859807]
 [2.22038617 0.70434583 1.47422905 1.63413118 1.9859865  1.43115841
  2.61594734]
 [1.68435607 1.82414766 1.60309226 1.25991822 2.22449292 1.45932154
  2.68769974]]


In [ ]:


# Assicuriamoci che il risultato abbia la forma corretta N x K
K = result.shape[-1]
result = result.reshape(N, K)

print(result)


In [22]:
my_function(array[1])

array([2.10809381, 1.71513197, 2.44287448, 2.61789654, 3.77081101,
       2.20231031, 2.91087549])

In [24]:
list(map(my_function, array))

[array([0.88466732, 1.95652242, 1.3155089 , 1.26292217, 1.33368544,
        1.72395779, 2.36197757]),
 array([2.10809381, 1.71513197, 2.44287448, 2.61789654, 3.77081101,
        2.20231031, 2.91087549]),
 array([0.74831751, 0.50029424, 1.97296542, 1.77336582, 1.09430418,
        2.16325591, 1.73738291]),
 array([2.41347268, 1.38375666, 1.61541072, 1.53863558, 2.62989694,
        2.08432661, 2.23705208]),
 array([1.44583837, 1.39928405, 0.7557402 , 1.29933141, 1.55190543,
        1.31910922, 2.02917937])]

In [9]:
 np.array([np.sum(array[0], axis=0), np.sum(array[0], axis=1)])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [25]:
np.apply_over_axes(my_function, array, [1])

TypeError: my_function() takes 1 positional argument but 2 were given

In [26]:
np.vectorize(my_function)(array)

AxisError: axis 1 is out of bounds for array of dimension 0

In [27]:
np.frompyfunc(my_function, 1, 1)(array)

AxisError: axis 1 is out of bounds for array of dimension 0

In [34]:
# random normal with mean 0.1 and std 1
x = np.random.normal(0.1, 1, size=(500,1))
x1 = -x

y = np.r_[np.ones((500,1)), np.zeros((500,1))]
x = np.r_[x, x1]

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [36]:
import xgboost as xgb
model = xgb.XGBClassifier()

In [47]:
model.fit(X_train, y_train)

XGBClassifier(base_score=0.1, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [48]:
model.predict_proba(X_test)[:,1]

array([0.394673  , 0.71097666, 0.58085424, 0.5399839 , 0.46381155,
       0.56020385, 0.46413717, 0.7163239 , 0.7163239 , 0.6454956 ,
       0.5126476 , 0.8787651 , 0.29666415, 0.6407782 , 0.5390801 ,
       0.23803996, 0.32930037, 0.3214673 , 0.6454956 , 0.59965396,
       0.54463947, 0.23803996, 0.3195454 , 0.61069643, 0.20547542,
       0.5399839 , 0.29268602, 0.1884615 , 0.4137764 , 0.29144844,
       0.89861375, 0.33559912, 0.585491  , 0.6373678 , 0.4167994 ,
       0.4399893 , 0.6496647 , 0.58085424, 0.47470775, 0.44436538,
       0.5126476 , 0.86431646, 0.4687736 , 0.47365424, 0.9217716 ,
       0.59965396, 0.4404437 , 0.33559912, 0.6984335 , 0.07355234,
       0.3817191 , 0.8858487 , 0.29666415, 0.46086812, 0.6454956 ,
       0.3195454 , 0.6407782 , 0.36027235, 0.4167994 , 0.6715103 ,
       0.91773176, 0.10107199, 0.3214673 , 0.5767981 , 0.55239433,
       0.47419623, 0.29144844, 0.6763592 , 0.3713147 , 0.7091393 ,
       0.3713147 , 0.42099625, 0.88206285, 0.29268602, 0.51264

In [63]:
np.vectorize(my_function,signature='(n,m)->(k)')(x)

array([[ 0.007971  ,  1.2651819 ,  0.52936496, ...,  1.47306015,
         0.33386088, -1.03937153],
       [-0.55596668,  2.04898679,  0.40731872, ...,  1.00550154,
        -0.1561146 ,  0.47037127],
       [-0.2329001 ,  1.50459794, -0.00239314, ...,  1.22768614,
        -0.98720537, -0.62498007],
       ...,
       [-0.46950649,  0.21086233,  1.90315175, ...,  0.02420046,
        -1.08280073, -1.1310705 ],
       [ 1.37584133,  0.17674597,  0.91208276, ..., -0.82003461,
        -0.44714985,  1.18919022],
       [-0.53578223,  0.0462862 , -0.35545921, ...,  0.20027965,
         0.10359928,  1.06125837]])

In [56]:
x = np.random.normal(0.1, 1, size=(500,10,1))

In [58]:
x.shape

(500, 10, 1)

In [61]:
np.diff(x[0],axis=0)

array([[ 1.2572109 ],
       [-0.73581695],
       [-0.24547159],
       [-0.08890476],
       [ 0.26235616],
       [-1.03914919],
       [ 2.05486457],
       [-1.13919927],
       [-1.37323241]])

In [70]:
my_function==(lambda x: x.flatten)

False

In [68]:
my_function = lambda x: x.flatten()

In [71]:
def ciao(x=lambda x: x.flatten()):
    return x

In [1]:
import time_irreversibility_estimator as tie
import numpy as np

In [2]:
x = np.random.normal(2., 1, size=(500,2,1))

In [3]:
q = x.cumsum(axis=1)

In [4]:
estimator = tie.TimeIrreversibilityEstimator(store=True)
estimator.fit_predict(q_forward=q,encoding_fun=lambda x: np.diff(x,axis=0))

np.float64(5.364557790756225)

In [7]:
estimator.models

[XGBClassifier(base_score=0.5, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, device=None, early_stopping_rounds=10,
               enable_categorical=False, eval_metric=None, feature_types=None,
               gamma=None, grow_policy=None, importance_type=None,
               interaction_constraints=None, learning_rate=0.3, max_bin=None,
               max_cat_threshold=None, max_cat_to_onehot=None,
               max_delta_step=None, max_depth=6, max_leaves=None,
               min_child_weight=None, missing=nan, monotone_constraints=None,
               multi_strategy=None, n_estimators=10000, n_jobs=None,
               num_parallel_tree=None, random_state=None, ...),
 XGBClassifier(base_score=0.5, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, device=None, early_stopping_rounds=10,
               enable_categorical=Fa

In [14]:
estimator.x_forward

array([[ 2.31994958],
       [ 2.94343737],
       [ 2.87780731],
       [ 1.48824447],
       [ 2.73601286],
       [ 2.45383764],
       [ 2.4450183 ],
       [ 1.30510251],
       [ 1.01566068],
       [ 2.02339114],
       [ 1.5927493 ],
       [ 1.87278505],
       [ 1.40247771],
       [ 3.22487363],
       [ 2.05634275],
       [ 2.54240157],
       [ 2.94575952],
       [ 1.84787852],
       [ 1.38388045],
       [ 1.45703184],
       [ 2.27862962],
       [ 2.43426481],
       [ 3.67671624],
       [ 1.95761944],
       [ 1.12581831],
       [ 1.11405483],
       [ 2.29866368],
       [ 2.07991804],
       [ 1.20101081],
       [ 2.18204925],
       [ 1.6651789 ],
       [ 4.13957391],
       [ 3.93731249],
       [ 3.88500764],
       [ 2.35638987],
       [ 3.03737296],
       [ 1.94864084],
       [ 1.50660386],
       [-0.53804007],
       [ 2.38969054],
       [ 1.51535147],
       [ 2.25010601],
       [ 1.73996218],
       [ 1.1314026 ],
       [ 1.12489285],
       [ 2